{
 "pytest_faulthandler": {
  "data": {},
  "type": "module"
 },
 "pytest_faulthandler._cancel_traceback_dump": {
  "data": {
   "lineno": 67,
   "symbols_in_volume": [
    "pytest_faulthandler.faulthandler",
    "pytest_faulthandler.timeout_support_available"
   ]
  },
  "type": "function"
 },
 "pytest_faulthandler.faulthandler": {
  "data": {
   "shadows": "faulthandler"
  },
  "type": "import"
 },
 "pytest_faulthandler.os": {
  "data": {
   "shadows": "os"
  },
  "type": "import"
 },
 "pytest_faulthandler.pytest": {
  "data": {
   "shadows": "pytest"
  },
  "type": "import"
 },
 "pytest_faulthandler.pytest_addoption": {
  "data": {
   "lineno": 6,
   "symbols_in_volume": [
    "int"
   ]
  },
  "type": "function"
 },
 "pytest_faulthandler.pytest_configure": {
  "data": {
   "lineno": 20,
   "symbols_in_volume": [
    "hasattr",
    "pytest_faulthandler.faulthandler",
    "pytest_faulthandler.os",
    "pytest_faulthandler.sys",
    "pytest_faulthandler.timeout_support_available"
   ]
  },
  "type": "function"
 },
 "pytest_faulthandler.pytest_enter_pdb": {
  "data": {
   "lineno": 75,
   "symbols_in_volume": [
    "pytest_faulthandler._cancel_traceback_dump",
    "pytest_faulthandler.pytest"
   ]
  },
  "type": "function"
 },
 "pytest_faulthandler.pytest_exception_interact": {
  "data": {
   "lineno": 82,
   "symbols_in_volume": [
    "pytest_faulthandler._cancel_traceback_dump",
    "pytest_faulthandler.pytest"
   ]
  },
  "type": "function"
 },
 "pytest_faulthandler.pytest_runtest_protocol": {
  "data": {
   "lineno": 50,
   "symbols_in_volume": [
    "pytest_faulthandler.faulthandler",
    "pytest_faulthandler.pytest",
    "pytest_faulthandler.timeout_support_available"
   ]
  },
  "type": "function"
 },
 "pytest_faulthandler.sys": {
  "data": {
   "shadows": "sys"
  },
  "type": "import"
 },
 "pytest_faulthandler.timeout_support_available": {
  "data": {
   "lineno": 41,
   "symbols_in_volume": [
    "hasattr",
    "pytest_faulthandler.faulthandler"
   ]
  },
  "type": "function"
 }
}