{
 "pytest_github_actions_annotate_failures": {
  "lineno": null,
  "symbols_in_volume": [],
  "type": "module"
 },
 "pytest_github_actions_annotate_failures.plugin": {
  "lineno": null,
  "symbols_in_volume": [],
  "type": "module"
 },
 "pytest_github_actions_annotate_failures.plugin._error_workflow_command": {
  "lineno": 55,
  "symbols_in_volume": [
   "collections.OrderedDict"
  ],
  "type": "function"
 },
 "pytest_github_actions_annotate_failures.plugin._escape": {
  "lineno": 70,
  "symbols_in_volume": [],
  "type": "function"
 },
 "pytest_github_actions_annotate_failures.plugin.pytest_runtest_makereport": {
  "lineno": 14,
  "symbols_in_volume": [
   "os.environ.get",
   "os.path.abspath",
   "os.path.relpath",
   "pytest.hookimpl"
  ],
  "type": "function"
 }
}